#' Title
#'
#' @param n integer dimension of the square matrix generated by this function
#' @param clique_fraction numeric proportion of the aforementioned matrix that is a clique
#' @param clique_edge_density numeric proportion of edges expected in the generated matrix's clique
#'
#' @return adjacency matrix with clique of size, density, and fraction specified in parameters
#' @export generate_partial_clique
#'
#' @examples
generate_partial_clique = function (n, clique_fraction, clique_edge_density) {
  if (!is.numeric(n) || n <= 0 || n != as.integer(n)) {
    stop("n must be a positive integer.")
  }
  if (!is.numeric(clique_fraction) || clique_fraction < 0 ||
      clique_fraction > 1) {
    stop("clique_fraction must be a numeric value between 0 and 1.")
  }
  if (!is.numeric(clique_edge_density) || clique_edge_density <
      0 || clique_edge_density > 1) {
    stop("clique_edge_density must be a numeric value between 0 and 1.")
  }
  m <- round(n * clique_fraction)
  num_edges <- round(clique_edge_density * m * (m - 1)/2)
  adj_mat <- matrix(0, nrow = n, ncol = n)
  diag(adj_mat) = 1
  if (n == 1) {
    return(adj_mat)
  }
  edge_count <- 0
  while (edge_count < num_edges) {
    i <- sample(1:m, 1)
    j <- sample(1:m, 1)
    if (i != j && adj_mat[i, j] == 0) {
      adj_mat[i, j] <- 1
      adj_mat[j, i] <- 1
      edge_count <- edge_count + 1
    }
  }
  output <- list(adj_mat = adj_mat)
  return(output)
}
